In [7]:
import numpy as np
z = np.zeros((2,4))
o = np.ones((2,4))

In [13]:
array_2d = np.arange(20).reshape(2,2,5)

In [14]:
array_2d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [23]:
array_2d.sum(axis = 2)

array([[10, 35],
       [60, 85]])

In [24]:
array_2d = np.arange(20).reshape(4,5)

In [25]:
array_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
array_2d.sum(axis=0).shape

(5,)

axis = 0 => down the row
axis = 1 => across the column

In [38]:
import pandas as pd

record_1 = {
     'name' : ["Ajay","mohit"],
     'age' : [20 , 24 ]
}
df = pd.DataFrame(record_1)
df

    name  age
0   Ajay   20
1  mohit   24

In [39]:
record_2 = {
     'name' : ["Aditi","monu"],
     'age' : [20 , 24 ]
}
df2 = pd.DataFrame(record_2)
df2

    name  age
0  Aditi   20
1   monu   24

In [44]:
pd.concat([df,df2],axis = 0)

    name  age
0   Ajay   20
1  mohit   24
0  Aditi   20
1   monu   24